memory_limit = 512M
upload_max_filesize = 100M
post_max_size = 100M
max_execution_time = 300
max_input_time = 300
max_input_vars = 10000

display_errors = On
display_startup_errors = On
log_errors = On
error_reporting = E_ALL
html_errors = On

date.timezone = America/Sao_Paulo

session.gc_maxlifetime = 1440
session.cookie_httponly = On
session.use_strict_mode = On
session.use_only_cookies = 1

realpath_cache_size = 4096k
realpath_cache_ttl = 600

opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=1
opcache.revalidate_freq=2
opcache.fast_shutdown=1
