services:
  app:
    build:
      context: .
      args:
        USER_ID: ${DOCKER_UID:-1000}
        GROUP_ID: ${DOCKER_GID:-1000}
    container_name: colegio-pense-nps-main
    restart: unless-stopped
    volumes:
      - .:/var/www
    ports:
      - "8080:80"