[supervisord]
nodaemon=true
user=www-data
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:php-fpm]
command=php-fpm -F
environment=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",PUPPETEER_SKIP_DOWNLOAD="true",PUPPETEER_EXECUTABLE_PATH="/usr/lib/chromium/chromium"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0