[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisor/supervisord.pid

[program:php-fpm]
command=php-fpm --nodaemonize
autostart=true
autorestart=true
priority=5
stdout_logfile=/var/log/supervisor/php-fpm.log
stderr_logfile=/var/log/supervisor/php-fpm-error.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB


[program:laravel-horizon]
command=php artisan horizon
autostart=true
autorestart=true
priority=15
startsecs=10
stopwaitsecs=30
stdout_logfile=/var/log/supervisor/horizon.log
stderr_logfile=/var/log/supervisor/horizon-error.log
stdout_logfile_maxbytes=100MB
stderr_logfile_maxbytes=100MB
directory=/var/www


[program:laravel-schedule]
command=/bin/sh -c "while true; do php /var/www/artisan schedule:run --no-interaction >> /var/log/supervisor/schedule.log 2>&1; sleep 60; done"
autostart=true
autorestart=true
startsecs=0
numprocs=1
stdout_logfile=/var/log/supervisor/schedule.log
stderr_logfile=/var/log/supervisor/schedule-error.log
stdout_logfile_maxbytes=100MB
stderr_logfile_maxbytes=100MB
directory=/var/www


[program:laravel-pulse]
command=php artisan pulse:check
autostart=true
autorestart=true
priority=20
startsecs=5
stopwaitsecs=10
stdout_logfile=/var/log/supervisor/pulse.log
stderr_logfile=/var/log/supervisor/pulse-error.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
directory=/var/www

[unix_http_server]
file=/var/run/supervisor/supervisor.sock
chmod=0777
username=admin
password=supervisor

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor/supervisor.sock
username=admin
password=supervisor
